baseurl = "https://wiigg.uk/"
title = "wiigg blog"
theme = "ghostwriter"
languageCode = "en-gb"
copyright = "Danny Wigg"
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Danny Wigg"
    profile = "https://twitter.com/wiigg"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "wiigg blog"
    description = "Thoughts, stories and ideas of a technologist."
    github = "https://github.com/wiigg"
    gitlab = "https://gitlab.com/XXX"
    linkedin = "https://linkedin.com/in/dannywigg/"
    gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/wiigg"
    stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "danny@wiigg.eu"
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
